server:
  port: 8081
api:
  filter: ?filters[tenantId][%24eq]=137
  host: https://api-core-q9s1.onrender.com/api
  auth: ${api.host}/auth/local
  lesson: ${api.host}/lessons
  teacher: ${api.host}/teachers
  member: ${api.host}/members
  group: ${api.host}/groups
  day: ${api.host}/days
  timeblock: ${api.host}/timeblocks
  subject: ${api.host}/subjects
  classroom: ${api.host}/classrooms
  request: ${api.host}/requests