server:
  port: 8081
api:
  filter: ?filters[tenantId][%24eq]=137
  host: https://api-core-q9s1.onrender.com
  lesson: ${api.host}/api/lessons
  teacher: ${api.host}/api/teachers
  auth: ${api.host}/api/auth/local